

POST http://localhost:3000/login
Content-Type:application/json
{
    "username":"Mallesh",
    "password":"Mallesh@123"
}

###

GET http://localhost:3000/tasks

###

POST http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/:id

###

PUT http://localhost:3000/tasks/:id

###


DELETE http://localhost:3000/tasks/:id 

###
